<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pari" failures="3" tests="14" name="Employee Project API Testing" time="32.378" errors="0" timestamp="2022-09-19T14:34:22 IST">
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="statusCodeTest" time="0.022"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="validateSuccessMessage" time="1.187"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="validateSuccessStatus" time="0.067"/>
  <testcase classname="com.employeeapi.testCases.TC002_Get_Single_Employee" name="checkEmpId" time="0.072"/>
  <testcase classname="com.employeeapi.testCases.TC002_Get_Single_Employee" name="statusCodeTest" time="0.009"/>
  <testcase classname="com.employeeapi.testCases.TC002_Get_Single_Employee" name="validateSuccessMessage" time="0.025"/>
  <testcase classname="com.employeeapi.testCases.TC002_Get_Single_Employee" name="validateSuccessStatus" time="0.028"/>
  <testcase classname="com.employeeapi.testCases.TC003_Post_Create_New_Employee" name="empName" time="0.017">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testCases.TC003_Post_Create_New_Employee.empName(TC003_Post_Create_New_Employee.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 32 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- empName -->
  <testcase classname="com.employeeapi.testCases.TC003_Post_Create_New_Employee" name="statusCodeTest" time="0.048">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testCases.TC003_Post_Create_New_Employee.statusCodeTest(TC003_Post_Create_New_Employee.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- statusCodeTest -->
  <testcase classname="com.employeeapi.testCases.TC003_Post_Create_New_Employee" name="validateSuccessStatus" time="0.004">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testCases.TC003_Post_Create_New_Employee.validateSuccessStatus(TC003_Post_Create_New_Employee.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 32 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateSuccessStatus -->
  <testcase classname="com.employeeapi.testCases.TC004_PUT_Update_Existing_Employee" name="statusCodeTest" time="0.005"/>
  <testcase classname="com.employeeapi.testCases.TC004_PUT_Update_Existing_Employee" name="updatedEmpNameTest" time="0.053"/>
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee" name="deleteMessageTest" time="0.035"/>
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee" name="statusCodeTest" time="0.004"/>
</testsuite> <!-- Employee Project API Testing -->
